### ISSUE TITLE
What is OP_SCAN_API_KEY in .env.example

### ISSUE THREAD

**Issue by PsychoPunkSage** [velodrome-finance/v1#11]
Hi,
Can anyone help me with what is "OP_SCAN_API_KEY" that has been used in .env.example?
How to get this API Key and what purpose does it serve here?

**Comment by pegahcarter** [comment]
Hey there!  This env variable is used to verify contracts on optimistic etherscan.  You can get an API key [here](https://optimistic.etherscan.io/myapikey).

**Comment by PsychoPunkSage** [comment]
Thanks
